export const COMMON_INGREDIENTS: string[] = [
  "water",
  "aqua",
  "eau",
  "glycerin",
  "niacinamide",
  "hyaluronic acid",
  "sodium hyaluronate",
  "panthenol",
  "allantoin",
  "tocopherol",
  "ascorbic acid",
  "citric acid",
  "sodium chloride",
  "xanthan gum",
  "dimethicone",
  "squalane",
  "aloe",
  "ceramide",
  "ceramide np",
  "ceramide ap",
  "ceramide eop",
  "cholesterol",
  "lactic acid",
  "salicylic acid",
  "glycolic acid",
  "urea",
  "shea butter",
  "petrolatum",
  "mineral oil",
  "cetearyl alcohol",
  "cetyl alcohol",
  "stearyl alcohol",
  "palmitoyl tripeptide-5",
  "trifluoroacetyl tripeptide-2",
  "caprooyl tetrapeptide-3",
  "acetyl hexapeptide-8",
  "ethylhexylglycerin",
  "aqua (eau)",
  "glyceryl stearate",
  "potassium sorbate",
  "acetic acid",
  "stearic acid",
  "caffeine",
  "phenoxyethanol",
  "levulinic acid",
  "sodium levulinate",
  "darutoside",
  "dextran",
  "ectoin",
  "myristyl nicotinate",
  "aloe barbadensis leaf juice",
  "caprylic/capric triglyceride",
  "helianthus annuus (sunflower) seed oil",
  "camellia japonica seed oil",
  "glyceryl stearate citrate",
  "albizia julibrissin bark extract",
  "fragaria ananassa (strawberry) seed oil",
  "sh-polypeptide-50",
  "leuconostoc/radish root ferment filtrate",
  "acmella oleracea extract",
  "camellia sinensis leaf extract",
  "lactobacillus ferment lysate",
  "punica granatum bark extract",
  "saccharomyces/xylinum/black tea ferment",
  "leontopodium alpinum flower/leaf extract",
  "oryza sativa (rice) extract",
  "phaseolus angularis seed extract",
  "saccharomyces/malpighia glabra (acerola) fruit ferment filtrate",
  "paeonia albiflora (peony) root extract",
  "adapalene",
  "benzoyl peroxide",
  "sulfur",
  "azelaic acid",
  "kaolin clay",
  "bentonite clay",
  "tea tree oil",
  "zinc pca",
  "willow bark extract",
  "witch hazel",
  "lipo-hydroxy acid",
  "lha",
  "succinic acid",
  "green tea extract",
  "egcg",
  "retinaldehyde",
  "granactive retinoid",
  "bakuchiol",
  "charcoal",
  "polyglutamic acid",
  "beta-glucan",
  "aloe vera",
  "snail mucin",
  "sodium pca",
  "trehalose",
  "snow mushroom",
  "tremella",
  "betaine",
  "pentylene glycol",
  "honey",
  "propolis",
  "xylitol",
  "sorbitol",
  "propylene glycol",
  "phytosphingosine",
  "fatty acids",
  "lecithin",
  "centella asiatica",
  "madecassoside",
  "asiaticoside",
  "natural moisturizing factors",
  "nmf",
  "colloidal oatmeal",
  "linoleic acid",
  "bisabolol",
  "calendula extract",
  "prebiotics",
  "postbiotics",
  "squalene",
  "evening primrose oil",
  "argan oil",
  "l-ascorbic acid",
  "vitamin c",
  "sodium ascorbyl phosphate",
  "ascorbyl glucoside",
  "tetrahexyldecyl ascorbate",
  "kojic acid",
  "alpha arbutin",
  "tranexamic acid",
  "hydroquinone",
  "licorice root extract",
  "glutathione",
  "mandelic acid",
  "cinnamic acid",
  "resveratrol",
  "viniferine",
  "ferulic acid",
  "phellinus linteus",
  "mulberry extract",
  "rice bran extract",
  "niacin",
  "gallic acid",
  "retinol",
  "copper peptides",
  "matrixyl 3000",
  "argireline",
  "palmitoyl tripeptide-1",
  "palmitoyl tetrapeptide-7",
  "coenzyme q10",
  "ubiquinone",
  "idebenone",
  "egf",
  "epidermal growth factor",
  "nmn",
  "nicotinamide mononucleotide",
  "pdrn",
  "polydeoxyribonucleotide",
  "dna-repair enzymes",
  "stem cell extracts",
  "ghk-cu",
  "sirtuins",
  "hexapeptide-9",
  "tripeptide-29",
  "rosemary oil",
  "malic acid",
  "tartaric acid",
  "gluconolactone",
  "lactobionic acid",
  "bromelain",
  "papain",
  "pumice",
  "jojoba esters",
  "vitamin e",
  "green tea polyphenols",
  "astaxanthin",
  "pycnogenol",
  "rosehip oil",
  "curcumin",
  "turmeric",
  "ginkgo biloba",
  "chamomile",
  "grapeseed oil",
  "marula oil",
  "pomegranate extract",
  "acai berry",
  "goji berry",
  "sea buckthorn oil",
  "baobab oil",
  "hemp seed oil",
  "blue tansy",
  "mugwort",
  "artemisia",
  "sodium laureth sulfate",
  "sles",
  "coco-betaine",
  "decyl glucoside",
  "caprylyl/capryl glucoside",
  "micelles",
  "polysorbate 20",
  "sodium methyl cocoyl taurate",
  "zinc oxide",
  "titanium dioxide",
  "avobenzone",
  "octocrylene",
  "homosalate",
  "octisalate",
  "tinosorb s",
  "tinosorb m",
  "mexoryl sx",
  "oxybenzone",
  "iron oxides",
  "sodium benzoate",
  "edta",
  "bht",
  "tocopheryl acetate",
  "alcohol denat",
  "carbomer",
  "mushroom extracts",
  "reishi",
  "shiitake",
  "algae extract",
  "bamboo extract",
  "royal jelly",
  "oat kernel oil",
  "comfrey root",
  "ginseng",
  "prickly pear",
  "hibiscus",
  "moringa oil",
  "ashwagandha",
  "gotu kola",
  "white tea extract",
  "sea salt",
  "lavender oil",
  "eucalyptus oil",
  "rose water",
  "jojoba oil",
  "lab-grown botanicals",
  "bio-fermented actives",
  "exosomes",
  "silicone substitutes",
  "neuro-cosmetics",
  "psychodermatological actives",
  "upcycled botanicals",
  "precision ferments",
  "filaggrin",
  "mitochondrial boosters",
  "nad+ boosters",
  "vegan pdrn",
  "stable vitamin c derivatives",
  "multi-weight hyaluronic complexes",
  "copper peptides 2.0",
  "algae-derived retinol alternatives",
  "skin-mind synergy ingredients",
  "keratin",
  "bio-active prebiotics",
  "arnelia deracao edrad",
  "n-formylmethionyl caprooyl tetrapeptide-1",
  "saccharomyces/magnolia glabra (acacia) fruit ferment filtrate",
  "passiflora incarnata flower extract",
  "vanilla planifolia fruit extract",
  "martynia notinate",
];
