#!/usr/bin/env python3
"""
Generate SQL seed statements from the waitlist XLSX file.

Default input:
  ./Waitlist email addresses (1).xlsx

Default output:
  ./supabase/seed_waitlist_special_pricing.sql
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from typing import Any

from openpyxl import load_workbook


def norm(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def norm_email(value: Any) -> str:
    return norm(value).lower()


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def to_boolish(value: Any) -> bool:
    text = norm(value).lower()
    return text in {"true", "1", "yes", "y"}


def promo_for(email: str, tier: str, billing_cycle: str) -> str:
    digest = hashlib.sha1(f"{email}|{tier}|{billing_cycle}".encode("utf-8")).hexdigest()[:8].upper()
    return f"WL_{digest}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--xlsx", default="Waitlist email addresses (1).xlsx")
    parser.add_argument("--sheet", default=None)
    parser.add_argument("--out", default="supabase/seed_waitlist_special_pricing.sql")
    parser.add_argument("--tier", choices=["premium", "pro"], default="premium")
    parser.add_argument("--billing-cycle", choices=["monthly", "annual"], default="monthly")
    parser.add_argument("--discount", type=int, default=50)
    parser.add_argument("--valid-days", type=int, default=14)
    parser.add_argument("--original-price", type=float, default=7.99)
    args = parser.parse_args()

    xlsx_path = Path(args.xlsx)
    if not xlsx_path.exists():
        raise SystemExit(f"Input file not found: {xlsx_path}")

    wb = load_workbook(xlsx_path, data_only=True)
    if args.sheet and args.sheet in wb.sheetnames:
        ws = wb[args.sheet]
    else:
        ws = wb[wb.sheetnames[0]]

    headers = [norm(ws.cell(1, c).value) for c in range(1, ws.max_column + 1)]
    col = {h: i + 1 for i, h in enumerate(headers) if h}

    required = ["EMAIL", "FIRSTNAME", "LASTNAME", "SKIN_TYPE", "SKIN_CONCERN", "ELIGIBLE"]
    missing = [k for k in required if k not in col]
    if missing:
        raise SystemExit(f"Missing required columns in sheet '{ws.title}': {', '.join(missing)}")

    discounted_price = round(args.original_price * (1 - (args.discount / 100)), 2)

    rows = []
    for r in range(2, ws.max_row + 1):
        email = norm_email(ws.cell(r, col["EMAIL"]).value)
        if not email:
            continue
        eligible = to_boolish(ws.cell(r, col["ELIGIBLE"]).value)
        if not eligible:
            continue

        first_name = norm(ws.cell(r, col["FIRSTNAME"]).value)
        last_name = norm(ws.cell(r, col["LASTNAME"]).value)
        skin_type = norm(ws.cell(r, col["SKIN_TYPE"]).value) or "Unsure"
        skin_concern = norm(ws.cell(r, col["SKIN_CONCERN"]).value) or "None"
        monthly_spend = norm(ws.cell(r, col.get("MONTHLY_SPEND_COST", 0)).value) if "MONTHLY_SPEND_COST" in col else ""

        rows.append(
            {
                "email": email,
                "first_name": first_name,
                "last_name": last_name,
                "skin_type": skin_type,
                "skin_condition": skin_concern,
                "money_spent": monthly_spend or "Unknown",
                "promo_code": promo_for(email, args.tier, args.billing_cycle),
            }
        )

    if not rows:
        raise SystemExit("No eligible rows found.")

    out = []
    out.append("-- Auto-generated by scripts/generate_waitlist_seed_sql.py")
    out.append(f"-- Source: {xlsx_path.name} (sheet: {ws.title})")
    out.append(f"-- Eligible rows: {len(rows)}")
    out.append("")
    out.append("BEGIN;")
    out.append("")

    for item in rows:
        out.append(
            "INSERT INTO public.waitlist (first_name, last_name, email, skin_type, skin_condition, money_spent)"
            f" VALUES ('{sql_escape(item['first_name'])}', '{sql_escape(item['last_name'])}', '{sql_escape(item['email'])}',"
            f" '{sql_escape(item['skin_type'])}', '{sql_escape(item['skin_condition'])}', '{sql_escape(item['money_spent'])}')"
            " ON CONFLICT (email) DO UPDATE SET"
            " first_name = EXCLUDED.first_name,"
            " last_name = EXCLUDED.last_name,"
            " skin_type = EXCLUDED.skin_type,"
            " skin_condition = EXCLUDED.skin_condition,"
            " money_spent = EXCLUDED.money_spent;"
        )

    out.append("")
    for item in rows:
        out.append(
            "INSERT INTO public.waitlist_special_pricing ("
            "waitlist_user_id, email, promo_code, tier_offering, billing_cycle, discount_percentage, original_price, discounted_price, valid_until, status, metadata"
            ") VALUES ("
            f"(SELECT id FROM public.waitlist WHERE LOWER(email) = LOWER('{sql_escape(item['email'])}') LIMIT 1),"
            f"'{sql_escape(item['email'])}',"
            f"'{sql_escape(item['promo_code'])}',"
            f"'{args.tier}',"
            f"'{args.billing_cycle}',"
            f"{args.discount},"
            f"{args.original_price:.2f},"
            f"{discounted_price:.2f},"
            f"(now() + interval '{args.valid_days} day'),"
            "'pending',"
            "'{}'::jsonb"
            ") ON CONFLICT (promo_code) DO UPDATE SET"
            " email = EXCLUDED.email,"
            " tier_offering = EXCLUDED.tier_offering,"
            " billing_cycle = EXCLUDED.billing_cycle,"
            " discount_percentage = EXCLUDED.discount_percentage,"
            " original_price = EXCLUDED.original_price,"
            " discounted_price = EXCLUDED.discounted_price,"
            " valid_until = EXCLUDED.valid_until,"
            " status = EXCLUDED.status;"
        )

    out.append("")
    out.append("COMMIT;")
    out.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {out_path} with {len(rows)} eligible waitlist rows.")


if __name__ == "__main__":
    main()
